config/routes.rb
Rails.application.routes.draw do

   root 'itineraries#index'
   get 'logout' => 'users#logout'
   patch 'sessions' => 'sessions#create'
  get '/auth/facebook/callback' => 'sessions#createfb'

     resources :users
     resources :itineraries
     resources :sessions
     resources :likes, only: [:create, :update, :destroy]

    resources :itineraries do
      resources :places, only: [:show, :new, :edit, :create, :update]
      resources :likes, only: [:create, :edit, :update, :destroy]
    end

    resources :places

end

app/models/itinerary.rb
class Itinerary < ActiveRecord::Base
  has_many :itinerary_places
  has_many :places, through: :itinerary_places
  has_many :likes
  has_many :liked_users, through: :likes, source: :user
  belongs_to :user
  accepts_nested_attributes_for :user

  validates :name, presence: true
  validates :description, presence: true
  #validates :password, presence: true

  validates_uniqueness_of :name

  def self.itin_ordered_list
    array = []
    Itinerary.all.each do |itin|
      array << {itin => itin.likes.count}
    end
    list = array.reduce Hash.new, :merge
    list = list.sort_by {|_key, value| value}.reverse
    temp = []
    list.each do |obj|
      temp << obj[0]
    end
    temp
  end





end

app/controllers/itineraries_controller.rb
class ItinerariesController < ApplicationController
before_action :find_and_set_itinerary!, only: [:show, :edit, :update, :destroy]
before_action :logged_in?, only: [:new, :create, :show, :edit, :update, :destroy]
before_action :current_user, only: [:new, :create, :show, :edit, :update, :destroy]

  def index
    if logged_in?
      @itineraries = Itinerary.itin_ordered_list
      @current_user = current_user
    else
      redirect_to new_user_path
    end
  end

  def new
    if current_user.username == 'admin'
      redirect_to itineraries_path
    else
    @itinerary = Itinerary.new
    end

  end

  def create
    #admin is not allowed to create new itineraries
    if @current_user.username != 'admin'
      @itinerary = Itinerary.new(itinerary_params, params[:user_id])
      if @itinerary.save
        @itinerary.user = User.find(session[:user_id])
        @itinerary.save
        redirect_to itinerary_path(@itinerary)
      else
        @current_user = User.find(session[:user_id])
        render :new
      end
    else
      redirect_to itineraries_path
    end
  end

  def show
    if @itinerary.nil?
      redirect_to itineraries_path
    else
      #binding.pry
      if current_user_like_itins(current_user,@itinerary)
        #binding.pry
        @liked = Like.where(user_id: current_user.id,itinerary_id: @itinerary.id).first
        #binding.pry
      else
        @like = Like.new
      end
      #@like = Like.find_by(user_id: @current_user.id, itinerary_id: @itinerary.id)
    end
  end

  def edit
    @itinerary = Itinerary.find(params[:id])

    if @current_user != @itinerary.user
      @itineraries = Itinerary.all
      render :index
    end
  end

  def update

    @itinerary = Itinerary.find(params[:id])
    if current_user == @itinerary.user && @itinerary.update(itinerary_params)
      redirect_to itinerary_path(@itinerary)
    else
      itin_update_fail(params)
      render :edit
    end
  end

  def destroy

    if @itinerary.user == @current_user
      @itinerary.destroy
      redirect_to itineraries_path
    else
      redirect_to itineraries_path
    end

  end

  private

  def itinerary_params
    params.require(:itinerary).permit(:name, :description)
  end

  def logged_in?
    !!session[:user_id]
  end

  def current_user
    @current_user = User.find(session[:user_id])
  end

  def itin_update_fail(params_hash)
    params = params_hash
    @user =  User.find(session[:user_id])
    @itinerary = Itinerary.find(params[:id])

    if @user == @itinerary.user
      if params[:itinerary][:name].empty? && params[:itinerary][:description].empty?
        @itinerary.errors.messages[:name] = ["Cannot leave name blank"]
        @itinerary.errors.messages[:description] = ["Cannot leave description blank"]
      elsif params[:itinerary][:name].empty?
        @itinerary.errors.messages[:name] = ["Cannot leave name blank"]
      elsif params[:itinerary][:description].empty?
        @itinerary.errors.messages[:description] = ["Cannot leave description blank"]
      end
    end
  end

  def find_and_set_itinerary!
    #binding.pry
    @itinerary = Itinerary.find(params[:id]) unless !Itinerary.all.ids.include?(params[:id].to_i)
    if @itinerary
      @itinerary
    else
      @itinerary = nil
    end
  end

  def current_user_like_itins(user, itinerary)
    arr =[]
    user.likes.each do |like|
      arr << like.itinerary_id
      arr
    end
    arr.include?(itinerary.id) ? true : false
  end

end

app/helpers/itineraries_helper.rb
module ItinerariesHelper

def current_user_likes_itins(user, itinerary)
  arr =[]
  user.likes.each do |like|
    arr << like.itinerary_id
    arr
  end
  arr.include?(itinerary.id) ? true : false
end

def ratings_average(itinerary)
  @itinerary = itinerary

  arr =[]
  if !@itinerary.likes.empty?
    @itinerary.likes.each do |like|
      arr << like.rating
    end
    avg = arr.sum/arr.length
  else
    avg = ""
  end

end

end

app/views/itineraries/_formitin.html.erb
<% if itinerary.errors.any? %>
  <div id="error_explanation">
    <h2>There were some errors:</h2>

    <ul>
      <% itinerary.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
    </ul>
  </div>
<% end %>


<div class="field">
  <%= f.text_field :name, placeholder: "Itinerary name" %>
</div></br>

<div class="field">
<%= f.text_area :description, placeholder: "Description" %>
</div></br>

<div class="actions">
<%= f.submit %>
</div>

app/views/itineraries/edit.html.erb
<div class="background-image-itin">

<div class="itin_edit">
<h1>Edit itinerary</h1>

<%= form_for(@itinerary) do |f| %>
<%= render partial: "formitin", locals: {itinerary: @itinerary, f: f} %>
<% end %>


  <% if !@itinerary.places.empty? %>
  <ul>
    <% @itinerary.places.each do |place| %>
      <!-- <li><%= link_to place.name, itinerary_place_path(@itinerary, place) %> -->
      <li><%= place.name %> <%= link_to "Delete site", itinerary_place_path(@itinerary, place), :method=> :put %>
    <% end %>
  </ul>
  <% end %>
<h4><%= link_to "<< Return to Itineraries index", itineraries_path %></h4>
</div>
</div>

app/views/itineraries/index.html.erb
<div class="background-image-itin">

<div class="itin_index clearfix max-width-4">
<h1>List of Itineraries</h1>
<div class="col col-4 "><h3><%= link_to "View List of Places", places_path %></h3></div>
<% if @current_user.username != 'admin'%>
  <div class="col col-4 "><h3><%= link_to "Create a new Itinerary", new_itinerary_path %></h3></div>
<% end %>

</div>

<div class="itin_index clearfix max-width-4">

<% @itineraries.each do |itin| unless @itineraries.empty? %>
  <div class="col col-4 "><%= link_to itin.name, itinerary_path(itin) %></div>
  <div class="col col-4 "> by <%= itin.user.username %></div>

    <% if itin.likes.empty? %>
    <div class="col col-4 "><%=  "NO ratings yet"  %><%= itin.likes.count == 1 ? " rating" : " ratings" unless itin.likes.empty? %></div>
    <% else %>
    <div class="col col-4 "><%=  ratings_average(itin)  %> star average <%=  itin.likes.count  %><%= itin.likes.count == 1 ? " rating" : " ratings" unless itin.likes.empty? %></div>
    <% end %>

<% end %>
<% end %>
</div>


</div>

app/views/itineraries/new.html.erb
<div class="background-image-itin">

<div class="itin_new">
<h1>Create a new itinerary</h1>

<%= form_for(@itinerary) do |f| %>
  <%= render partial: "formitin", locals: {itinerary: @itinerary, f: f} %>
<% end %>
<h4><%= link_to "<< Return to Itineraries index", itineraries_path %></h4>
</div>
</div>

app/views/itineraries/show.html.erb
<div class="background-image-itin">


<div class="itin_show">
<h1>Itinerary Details<h1>


<h2>Name: <%= @itinerary.name %> by <%= @itinerary.user.username %></h2>
<h2>Description: <%= @itinerary.description %></h2>

<div class="itin_show_add clearfix max-width-4">
<div class="col col-4 ">Places Visited</div>
<% if @current_user == @itinerary.user %>
<div class="col col-8 right-align"><%= link_to "Add places", new_itinerary_place_path(@itinerary) %>
<%= link_to "Edit Itinerary", edit_itinerary_path(@itinerary) %>
<%= link_to "Delete Itinerary", itinerary_path(@itinerary), :method=> :delete %></div>
<% end %>
</div>

<% if !@itinerary.places.empty? %>
<ul>
  <% @itinerary.places.each do |place| %>
    <p><li><%= link_to place.name, itinerary_place_path(@itinerary, place) %></p>
  <% end %>
</ul>
<% end %></br>


<% if @current_user != @itinerary.user && !check_if_admin(@current_user) && !current_user_likes_itins(@current_user, @itinerary) %>

<%= form_for [@itinerary, @like] do |f| %>

<% if @current_user.username != 'admin' %>
  <div class="field">
  <%= f.label "Add rating" %>
  <%= f.collection_select :rating, ['1','2','3','4','5'], :to_i, :to_i %></br></br>
  </div>
<% end %>

<%= f.submit "Add rating" %>
<% end %>

<% end %></br>

<% if @current_user != @itinerary.user && !check_if_admin(@current_user) && current_user_likes_itins(@current_user, @itinerary) %>

<%= form_for [@itinerary, @liked], :url => url_for(:controller => 'likes', :action => 'update') do |f| %>
<h3>Your current rating is <%= @liked.rating %></h3>
<% if @current_user.username != 'admin' %>
  <div class="field">
  <%= f.label "Change rating" %>
  <%= f.collection_select :rating, ['1','2','3','4','5'], :to_i, :to_i %></br></br>
  </div>
<% end %>

<%= f.submit "Change rating" %>
<% end %></br>

<%= button_to "Delete Rating", {:controller => :likes, :action => 'destroy', :id => @liked.id }, :method => :delete %>
<% end %>


<h4><%= link_to "<< Return to Itineraries index", itineraries_path %></h4>
</div>

</div>