config/routes.rb
Rails.application.routes.draw do

   root 'itineraries#index'
   get 'logout' => 'users#logout'
   patch 'sessions' => 'sessions#create'
  get '/auth/facebook/callback' => 'sessions#createfb'

     resources :users
     resources :itineraries
     resources :sessions
     resources :likes, only: [:create, :update, :destroy]

    resources :itineraries do
      resources :places, only: [:show, :new, :edit, :create, :update]
      resources :likes, only: [:create, :edit, :update, :destroy]
    end

    resources :places

end

app/models/place.rb
require 'pry'
class Place < ActiveRecord::Base
  has_many :itinerary_places
  has_many :itineraries, through: :itinerary_places
  #has_many :users
  has_many :users, through: :itineraries
  validates :name, presence: true, uniqueness: { scope: :address,
    message: "one location per borough" }
  validates :address, presence: true
  scope :boro, ->(add) { where("address = ?", add)}
  scope :ordlist, -> { order("name").order("address")}
  scope :manhattan, -> { where(address: 'Manhattan') }
  scope :queens, -> { where(address: 'Queens') }
  scope :statenisland, -> { where(address: 'Staten Island') }
  scope :bronx, -> { where(address: 'Bronx') }
  scope :brooklyn, -> { where(address: 'Brooklyn') }
  scope :everything, -> { where(address: 'All') }

  def self.find_by_name_address(params_hash)
    #find all instances with matching parameters
    #binding.pry
    params = params_hash
    name = params[:place][:name].split(/(\W)/).map(&:capitalize).join
    address = params[:place][:address]
    place = Place.where(name: name, address: address)
    if !place.nil?
      place
    else
      nil
    end
  end

  def name_with_id
    "#{name}. #{address}"
  end
end

app/controllers/places_controller.rb
require 'pry'
class PlacesController < ApplicationController
before_action :check_if_admin!, only: [:edit, :destroy]

  def index
    if params.keys.include?("borough")
      params[:borough] != "All" ? @places = Place.boro(params[:borough]).ordlist : @places = Place.all.ordlist
    else
      @places = Place.all.ordlist
    end
  end

  def edit
    @place = Place.find(params[:id]) unless !Place.all.ids.include?(params[:id].to_i)
    if !@place.nil? && check_if_admin
      @place = Place.find(params[:id])
      @current_user = current_user
    else
      redirect_to places_path
      #add alert message
    end
  end


  def new
    #if user is admin then allow path place_path(@place) after making place.new places/1

    if check_if_admin
      @place = Place.new
      @current_user = current_user
      #binding.pry
      #if regular user then params[:itinerary_id] must exist and the itinerary should exist
    elsif params[:itinerary_id] && !Itinerary.exists?(params[:itinerary_id])
      redirect_to itineraries_path, alert: "Itinerary not found."
      #msg alert saying access denied or itin not present
    elsif params[:itinerary_id].nil? && !check_if_admin
      redirect_to places_path
    else
      @place = Place.new
      @current_user = current_user
      @itinerary = Itinerary.find(params[:itinerary_id])
      #@place.itineraries << @itinerary
    end

  end

  def create
    ### admin can create a new place
    if current_user.username == 'admin'
      if params[:place][:name].empty? || params[:place][:address].empty?
        @place = Place.new(place_params)
        @place.save
        @current_user = current_user
        render :new
      elsif !params[:place][:name].empty? && !params[:place][:address].empty?
        @place = Place.find_or_create_by(name: proper_case(params[:place][:name]), address: params[:place][:address])
        redirect_to places_path
      end
    end
    #nonn-admin users can create places only under itineraries
    if current_user.username != 'admin'
      @itinerary = Itinerary.find(params[:itinerary_id])
      if correct_itin_user(@itinerary) #add if current user is correct
        @itinerary = Itinerary.find(params[:itinerary_id])
        method = user_create_number(params)
        if method == 1
          @place = Place.find(params[:place][:id])
          place_itin_association(params,@place)
          redirect_to itinerary_path(@itinerary)
        elsif method == 2
          @place = Place.where(name: proper_case(params[:place][:name]), address: params[:place][:address]).first_or_create
          place_itin_association(params,@place)
          redirect_to itinerary_path(@itinerary)
        else
          @itinerary = Itinerary.find(params[:itinerary_id])
          @place = Place.new
          @place.errors.messages[:selection] = ["Choose existing place or create a new one with both fields"]
          @current_user = current_user
          render :new
        end
      else
        redirect_to itineraries_path
      end
    end


  end

  def show
    @place = Place.find(params[:id]) unless !Place.all.ids.include?(params[:id].to_i)
    if !@place.nil?
      @place = Place.find(params[:id])
    else
      redirect_to places_path
      #add alert message
    end
  end

  def update
    ####only admin can add address and edit name
    @place = Place.find(params[:id])
    @place_existing = Place.find_by_name_address(params) unless !check_if_admin
    if @place.valid? && check_if_admin
      if @place_existing.empty?
        if !params[:place][:name].empty? && !params[:place][:address].empty?
          @place.update(name: proper_case(params[:place][:name])) unless params[:place][:name].empty?
          @place.update(address: params[:place][:address]) unless params[:place][:address].empty?
        end
        redirect_to places_path
      else
        @places = Place.all.order(:name, address: :asc)
        render :index
      end
    elsif params.keys.include?("itinerary_id") && !check_if_admin
      ####regular user updates itinerary to exclude place
      @itinerary = Itinerary.find(params[:itinerary_id])
      if !params[:itinerary_id].empty? && !params[:id].empty? && @itinerary.user == current_user
        # @itinerary = Itinerary.find(params[:itinerary_id])
        @place = Place.find(params[:id])
        @itinerary.places.delete(Place.find_by(id: params[:id]))
        @itinerary.save
        redirect_to itinerary_path(@itinerary)
      else
        redirect_to itineraries_path
      end
    else
      redirect_to places_path
    end
    #user removes place from own itinerary

  end

  def destroy
    @place = Place.find(params[:id])
    @place.destroy
    redirect_to places_path
  end

  private

  def place_params
    params.require(:place).permit(:name, :address)
  end

  def logged_in?
    !!session[:user_id]
  end

  def current_user
    User.find(session[:user_id])
  end

  def correct_itin_user(itinerary)
    @itinerary = itinerary
    current_user == @itinerary.user
  end

  def proper_case(string)
    string.split(/(\W)/).map(&:capitalize).join
  end

  def place_itin_association(params_hash,place)
    #binding.pry
    params = params_hash
    @place = place
    @itinerary = Itinerary.find(params[:itinerary_id])
    @place.itineraries << @itinerary unless @itinerary.places.include?(@place)
    @place.save
  end

  def check_if_admin
    current_user.username == 'admin'
  end

  def check_if_admin!
    unless check_if_admin
      redirect_to itineraries_path
    end
  end

  def user_create_number(params)
    params = params
    num = 0;
    if !params[:place][:id].empty? && (params[:place][:name].empty? && params[:place][:address].empty?)
      num = 1
    elsif params[:place][:id].empty? && (!params[:place][:name].empty? && !params[:place][:address].empty?)
      num = 2
    else
      num = 3
    end
    num
  end

end

app/helpers/places_helper.rb
module PlacesHelper

  def check_if_admin(current_user)
    current_user.username == 'admin'
  end

end

app/views/places/_form.html.erb
<% if place.errors.any? %>
    <div id="error_explanation">
      <h2>There were some errors:</h2>

      <ul>
        <% place.errors.full_messages.each do |message| %>
          <li><%= message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>


<div class="field">
<%= f.label "Add New Place Name" %>
<%= f.text_field :name %>
</div></br>

<div class="field">
<%= f.label "Address" %>
<%= f.select :address, [[''], ['Manhattan'], ['Queens'], ['Staten Island'], ['Brooklyn'], ['Bronx']] %>
</div></br>

app/views/places/edit.html.erb
<div class="background-image-place">

<div class="places_new">

<h1>Edit Place Form</h1>

<%= form_for (@place) do |f| %>
  <!-- <%= f.collection_check_boxes :name, Place.all, :id, :name %></br></br> -->
<%= render partial: "form", locals: {place: @place, f: f} %>
<%= f.hidden_field :current_user_id, value: @current_user.id %>
<%= f.submit "Edit place" %>
<% end %>

<h3><%= link_to "<< Return to List of Places", places_path %></h3>
</div>
</div>

app/views/places/index.html.erb
<div class="background-image-place">

<div class="places_new">

<h1>List of places</h1>

<%= form_tag(places_path, method: :get) do %>
<%= select_tag "borough", options_for_select(['All', 'Manhattan','Queens','Brooklyn','Bronx','Staten Island']) %>
<%= submit_tag "View by borough" %>
<% end %></br>

<% if current_user.username == 'admin' %>
<div class="places_index clearfix max-width-3">
  <div class="col col-4"><h3>Name</h3></div>
  <div class="col col-4 "><h3>Location</h3></div>
  <div class="col col-4 "><h3><%= link_to "Add New Place", new_place_path %></h3></div></br>

<% @places.each do |place| unless @places.empty? %>
  <div class="col col-4 "><%= link_to place.name, place_path(place) %></div>
  <div class="col col-4"><%= place.address unless place.address.nil? %></div>

    <% if current_user.username == 'admin' %>
    <div class="col col-2 "><%= link_to "Edit place", edit_place_path(place) %></div>
    <div class="col col-2 "><%= link_to "Delete Place", place_path(place), :method=> :delete %></div>
    <% else %>

    <% end %>

<% end %>

<% end %>

</div></br>
<% end %>

<% if current_user.username != 'admin' %>
<div class="places_index clearfix max-width-3">
  <div class="col col-6"><h3>Name</h3></div>
  <div class="col col-6 "><h3>Location</h3></div>


<% @places.each do |place| unless @places.empty? %>
  <div class="col col-6 "><%= link_to place.name, place_path(place) %></div>
  <div class="col col-6"><%= place.address unless place.address.nil? %></div>
<% end %>

<% end %>

</div></br>
<% end %>

<%= link_to "<< Return to Itineraries Index", itineraries_path %></br>
</div>
</div>

app/views/places/new.html.erb
<div class="background-image-place">

<div class="places_new">
<h2>Add existing or create new place for itinerary</h2>

<% if @current_user.username != 'admin' %>
    <h2><%= @itinerary.name %> by <%= @itinerary.user.username %></h2>
    <h2><%= @itinerary.description %></h2>

    <% if !@itinerary.places.empty? %>
    <ul>
      <% @itinerary.places.each do |place| %>
        <li><%= place.name  %></li>
      <% end %>
    </ul>
    <% end %>

<% end %>

    <%= form_for [@itinerary, @place] do |f| %>
    <!-- <%= f.collection_check_boxes :name, Place.all, :id, :name %></br></br> -->

    <%= render partial: "form", locals: {place: @place, f: f} %>

    <% if @current_user.username != 'admin' %>
      <div class="field">
      <%= f.label "Add Existing Place" %>
      <%= f.collection_select :id, Place.all, :id, :name_with_id, :include_blank => true %></br></br>
      </div></br>
    <% end %>

    <%= f.submit "Add site" %>
    <% end %>

</div>
</div>

app/views/places/show.html.erb
<div class="background-image-place">

<div class="places_new">
<h1>Show page for place</h1>

<h2>Name: <%= @place.name %></h2>
<h2>Location: <%= @place.address %></h2>

<%= link_to "<< Return to Itineraries Index", itineraries_path %></br>
<%= link_to "<< Return to List of Places", places_path %>
</div>
</div>